### ISSUE TITLE
while scraping the scraper throws error and stops if it is not able to find an element

### ISSUE THREAD

**Issue by h3xh4wk** [h3xh4wk/expat#12]
while scraping the scraper throws error and stops if it is not able to find an element

Intended behavior is that it should continue scraping the page. Also it will be great if scraped information is written in an external file rather than in memory because the collected info will be lost due to an unexpected error.
 
```bash
Traceback (most recent call last):
  File "/usr/lib/python3.7/pdb.py", line 1703, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python3.7/pdb.py", line 1572, in _runscript
    self.run(statement)
  File "/usr/lib/python3.7/bdb.py", line 585, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/jitendra/shared/expat/utils/py/selenium_scraper.py", line 116, in <module>
    scraper.scrape()
  File "/home/jitendra/shared/expat/utils/py/selenium_scraper.py", line 61, in scrape
    self.scrape_page()
  File "/home/jitendra/shared/expat/utils/py/selenium_scraper.py", line 45, in scrape_page
    ".provider-link-details .icon-mail+a").get_attribute(
  File "/home/jitendra/shared/pyselenium/selenium/webdriver/remote/webelement.py", line 461, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/home/jitendra/shared/pyselenium/selenium/webdriver/remote/webelement.py", line 700, in find_element
    {"using": by, "value": value})['value']
  File "/home/jitendra/shared/pyselenium/selenium/webdriver/remote/webelement.py", line 672, in _execute
    return self._parent.execute(command, params)
  File "/home/jitendra/shared/pyselenium/selenium/webdriver/remote/webdriver.py", line 317, in execute
    self.error_handler.check_response(response)
  File "/home/jitendra/shared/pyselenium/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: .provider-link-details .icon-mail+a
```

**Comment by h3xh4wk** [comment]
[fixed this issue](https://github.com/stupidnetizen/expat/commit/abc5f48810a00c83ae7b43efe9a5246b0a739761)
Now scraper scrapes until nextpage function doesn't fail and scraping a page continues on `NoSuchElementException` .
